config/routes.rb
Rails.application.routes.draw do

  resources :academies
  resources :instructions, only: [:index, :edit, :update]
  resources :configs, only: [:show, :edit, :update]
  get '/results/saisie', to: 'results#saisie'

  resources :results
  resources :notes
  resources :tests
  resources :levels
  resources :classrooms
  resources :school_types
  resources :cycles
  resources :circonscriptions
  resources :documents
  root 'welcome#index'
  get '/global/:id', to: 'welcome#global'
  get '/global', to: redirect('/global/0'), as: :global
  get '/users/:id/active', to: 'users#active', as: :active
  post '/users/:id/send_activation', to: 'users#send_activation', as: :send_activation

  get '/users/emails', to: 'users#emails', as: :emails_path

  get '/faq', to: 'welcome#faq', as: :faq

  get '/account', to: 'users#account', as: :account

  resources :users

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :password_resets, only: [:new, :create, :edit, :update]

  post '/users/new_teacher', to: 'users#create_with_existing_classroom'

  get '/classroom/complet', to: 'classrooms#complet', as: :classroom_complet

  delete '/classrooms/:id/users/:user_id', to: 'classrooms#del_user', as: :classroom_del_user

  get '/tests/:id/documents', to: 'tests#documents'

end

app/models/academie.rb
class Academie < ActiveRecord::Base
end

app/models/circonscription.rb
class Circonscription < ActiveRecord::Base
  has_many :users
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :circonscription
  belongs_to :school_type
  has_and_belongs_to_many :users
  has_and_belongs_to_many :levels
  has_and_belongs_to_many :cycles
  has_many :results

  def cycle?(cycle_id)
    return self.cycle_ids.include?(cycle_id)
  end

  def level?(level_id)
    return self.level_ids.include?(level_id)
  end

end

app/models/config.rb
class Config < ActiveRecord::Base
  has_attached_file :image_fond, styles: { medium: "1200x1200", thumb: "100x100" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image_fond, content_type: /\Aimage\/.*\z/
  has_attached_file :bandeau, styles: { medium: "480x150", thumb: "100x100" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :bandeau, content_type: /\Aimage\/.*\z/
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  has_and_belongs_to_many :classrooms
  has_many :results
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :cycle
  belongs_to :test
  validates :cycle, :test, :presence => true
  has_attached_file :file
  validates_attachment_presence :file
  validates_attachment_file_name :file, matches: [/pdf\z/, /zip\z/]
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_and_belongs_to_many :classrooms
end

app/models/note.rb
class Note < ActiveRecord::Base
  has_attached_file :picto, styles: { medium: "300x300>", thumb: "100x100>", xs: "50x50" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picto, content_type: /\Aimage\/.*\z/
  has_many :results
end

app/models/result.rb
class Result < ActiveRecord::Base
  validates :classroom_id, :test_id, :cycle_id, :note_id, :user_id, :presence => true
  belongs_to :classroom
  belongs_to :test
  belongs_to :cycle
  belongs_to :note
  belongs_to :user
end

app/models/school_type.rb
class SchoolType < ActiveRecord::Base
  has_many :classrooms
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :results
  has_attached_file :picto, styles: { medium: "300x300>", thumb: "100x100>", xs: "50x50" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picto, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :first_name, :last_name, :presence => true

  validate :verify_email

  has_and_belongs_to_many :classrooms
  has_many :results

  acts_as_authentic do |c|
    c.log_in_after_create = false
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end

  def name
    return "#{self.first_name} #{self.last_name.upcase}"
  end

  private
    def verify_email
      address = self.email.downcase
      match = Academie.pluck(:name).detect { |name| address.end_with?(name) }
      errors.add(:email, "Votre courriel ne correspond pas à une adresse académique") unless match
    end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  before_action :only_admins
  before_action :set_config, only: [:show, :edit, :update, :destroy]

  # GET /configs
  # GET /configs.json
  def index
    @configs = Config.all
  end

  # GET /configs/1
  # GET /configs/1.json
  def show
  end

  # GET /configs/new
  def new
    @config = Config.new
  end

  # GET /configs/1/edit
  def edit
  end

  # POST /configs
  # POST /configs.json
  def create
    @config = Config.new(config_params)

    respond_to do |format|
      if @config.save
        format.html { redirect_to @config, notice: 'Config was successfully created.' }
        format.json { render :show, status: :created, location: @config }
      else
        format.html { render :new }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /configs/1
  # PATCH/PUT /configs/1.json
  def update
    respond_to do |format|
      if @config.update(config_params)
        format.html { redirect_to root_path, notice: 'Config was successfully updated.' }
        format.json { render :show, status: :ok, location: @config }
      else
        format.html { render :edit }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configs/1
  # DELETE /configs/1.json
  def destroy
    @config.destroy
    respond_to do |format|
      format.html { redirect_to configs_url, notice: 'Config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config
      @config = Config.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_params
      params.require(:config).permit(:image_fond, :bandeau, :inscription_automatique)
    end
end

app/helpers/academies_helper.rb
module AcademiesHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def delete user
    if user.results.count>0
      user.active = false
      user.save
      return false
    else
      user.classrooms.each do |classroom|
        unless classroom.users.count>1
          classroom.destroy
        end
      end
      user.destroy
      return true
    end
  end

end

app/views/configs/_form.html.erb
<%= form_for(@config) do |f| %>
  <% if @config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@config.errors.count, "error") %> prohibited this config from being saved:</h2>

      <ul>
      <% @config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_fond %><br>
    <%= f.file_field :image_fond %>
  </div>
  <div class="field">
    <%= f.label :bandeau %><br>
    <%= f.file_field :bandeau %>
  </div>
  <div class="field">
    <%= f.label :inscription_automatique %><br>
    <%= f.check_box :inscription_automatique %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/configs/edit.html.erb
<h1>Editing Config</h1>

<%= render 'form' %>

app/views/configs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Configs</h1>

<table>
  <thead>
    <tr>
      <th>Image fond</th>
      <th>Bandeau</th>
      <th>Inscription automatique</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @configs.each do |config| %>
      <tr>
        <td><%= config.image_fond %></td>
        <td><%= config.bandeau %></td>
        <td><%= config.inscription_automatique %></td>
        <td><%= link_to 'Show', config %></td>
        <td><%= link_to 'Edit', edit_config_path(config) %></td>
        <td><%= link_to 'Destroy', config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Config', new_config_path %>

app/views/configs/new.html.erb
<h1>New Config</h1>

<%= render 'form' %>

<%= link_to 'Back', configs_path %>

app/views/configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image fond:</strong>
  <%= image_tag @config.image_fond.url(:thumb) %>
</p>

<p>
  <strong>Bandeau:</strong>
  <%= image_tag @config.bandeau.url(:thumb) %>
</p>

<p>
  <strong>Inscription automatique:</strong>
  <%= @config.inscription_automatique %>
</p>

<%= link_to 'Edit', edit_config_path(@config) %> |