config/routes.rb
Rails.application.routes.draw do

  resources :academies
  resources :instructions, only: [:index, :edit, :update]
  resources :configs, only: [:show, :edit, :update]
  get '/results/saisie', to: 'results#saisie'

  resources :results
  resources :notes
  resources :tests
  resources :levels
  resources :classrooms
  resources :school_types
  resources :cycles
  resources :circonscriptions
  resources :documents
  root 'welcome#index'
  get '/global/:id', to: 'welcome#global'
  get '/global', to: redirect('/global/0'), as: :global
  get '/users/:id/active', to: 'users#active', as: :active
  post '/users/:id/send_activation', to: 'users#send_activation', as: :send_activation

  get '/users/emails', to: 'users#emails', as: :emails_path

  get '/faq', to: 'welcome#faq', as: :faq

  get '/account', to: 'users#account', as: :account

  resources :users

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :password_resets, only: [:new, :create, :edit, :update]

  post '/users/new_teacher', to: 'users#create_with_existing_classroom'

  get '/classroom/complet', to: 'classrooms#complet', as: :classroom_complet

  delete '/classrooms/:id/users/:user_id', to: 'classrooms#del_user', as: :classroom_del_user

  get '/tests/:id/documents', to: 'tests#documents'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :first_name, :last_name, :presence => true

  validate :verify_email

  has_and_belongs_to_many :classrooms
  has_many :results

  acts_as_authentic do |c|
    c.log_in_after_create = false
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end

  def name
    return "#{self.first_name} #{self.last_name.upcase}"
  end

  private
    def verify_email
      address = self.email.downcase
      match = Academie.pluck(:name).detect { |name| address.end_with?(name) }
      errors.add(:email, "Votre courriel ne correspond pas à une adresse académique") unless match
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UsersHelper

  before_action :only_admins_or_pilotes, only: [:index]
  before_action :only_admins, except: [:index, :new, :create, :create_with_existing_classroom, :active, :reset_password, :send_activation, :account, :destroy, :update]
  before_action :only_logged_users, except: [:new, :create, :active, :reset_password]
  before_action :set_user, only: [:show, :destroy, :edit, :update, :active, :reset_password, :send_activation]
  before_action :only_owner, only: [:destroy]
  before_action :set_lists, only: [:new, :create, :destroy, :edit, :update]

  def index
    @users = nil
    if params["type"]=="admins"
      @users = User.order(:created_at).where(admin: true)
    elsif params["type"]=="pilotes"
      @users = User.order(:created_at).where(pilote: true)
    else
      @users = User.order(:created_at).where(admin: [false, nil], pilote: [false, nil])
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def new
    @user = User.new
    @consigne = Instruction.where(name:"inscription").first
  end

  def create
    @user = User.new(user_params)
    @consigne = Instruction.where(name:"inscription").first
    @user.active = false # temporaire en attendant d'avoir la confirmation par email
    if @user.save
      message = "L'utilisateur #{@user.name} a été créé."
      unless @user.active
        message += "Un email vous a été envoyé sur votre boîte académique pour valider votre inscription. Le lien sera valide pendant 24h."
        PasswordResetMailer.activate_account(@user).deliver_now
      end
      email_etablissement = params["email_etablissement"]
      if classroom = Classroom.create(name: params["class_name"],
                                      circonscription_id: params["circonscription_id"],
                                      ecole: params["etablissement"],
                                      school_type_id: params["school_type_id"],
                                      email_etablissement: email_etablissement,
                                      other_level: params["other_classroom"])
        @cycles.each do |cycle|
         if params[cycle.name]
           classroom.cycles << cycle unless classroom.cycles.include?(cycle)
         end
        end
        @levels.each do |level|
         if params[level.name]
           classroom.levels << level unless classroom.levels.include?(level)
         end
        end
        @user.classrooms << classroom
        redirect_to root_path, notice: message
      else
        @user.delete
        render :action => :new
      end
    else
      render :action => :new
    end
  end

  def create_with_existing_classroom
    new = false
    @consigne = Instruction.where(name:"inscription").first
    classroom = Classroom.find(params["classroom_id"])
    if classroom
      email = params["email"]
      @user = User.where(email: email).first
      unless @user
        @user = User.new
        @user.first_name = params["first_name"]
        @user.last_name = params["last_name"]
        @user.email = email
        @user.active = false # temporaire en attendant d'avoir la confirmation par email
        password = SecureRandom.base64(6)
        @user.password = password
        @user.password_confirmation = password
        new = true
      end
      @user.classrooms << classroom
      if @user.save
        PasswordResetMailer.reset_email(@user, "#{current_user.name} vous a inscrit à une classe pour le Défiweb.\nPour y participer vous devez cliquer sur ce lien et vous créer un mot de passe.").deliver_now if new
        redirect_to root_path, notice: "Nouvel enseignant ajouté"
      else
        redirect_to root_path, notice: "Impossible d'ajouter le nouvel enseignant"
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if delete @user
      respond_to do |format|
        format.html { redirect_to users_url, notice: "L'utilisateur #{@user.name} a été supprimé" }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to users_url, notice: "L'utilisateur #{@user.name} a déjà saisi des résultats, il a donc été désactivé" }
        format.json { head :no_content }
      end
    end
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      parametres = user_params
      if @user.update(parametres)
        format.html {
          if (current_user.admin or current_user.pilote)
            redirect_to users_path, notice: "L'utilisateur #{@user.name} vient d'être mis à jour"
          else
            redirect_to root_path, notice: "L'utilisateur #{@user.name} vient d'être mis à jour"
          end
        }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/1/active
  def active
    if @user.perishable_token==params["token"]
      @user.active = true
      @user.save
      redirect_to sign_in_path, notice: "Votre compte a été activé"
    else
      redirect_to sign_in_path, notice: "Votre lien n'est plus valide"
    end
  end

  # POST /users/1/send_activation
  def send_activation
    PasswordResetMailer.activate_account(@user).deliver_now unless @user.active
  end

  # GET /account
  def account
    @user = current_user
  end

  # GET /users/emails
  def emails
    @cycles = {}
    users = User.where(active: true, bloque: [false, nil]).order(:last_name, :first_name)
    Cycle.all.each do |cycle|
      text = ""
      users.each do |user|
        user.classrooms.each do |classroom|
          if classroom.cycle_ids.include?(cycle.id)
            add = "#{user.email} #{user.last_name} #{user.first_name}\n"
            text << add unless text.include?(add)
          end
        end
      end
      @cycles[cycle.name] = text
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_lists
      @circonscriptions = Circonscription.order(:name)
      @cycles = Cycle.order(:name)
      @levels = Level.order(:order)
      @school_types = SchoolType.order(:name)
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :active, :admin, :pilote, :bloque)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def delete user
    if user.results.count>0
      user.active = false
      user.save
      return false
    else
      user.classrooms.each do |classroom|
        unless classroom.users.count>1
          classroom.destroy
        end
      end
      user.destroy
      return true
    end
  end

end

app/views/users/_classrooms.html.erb
<div id="toolbar">
  <%= link_to new_classroom_path, class: "btn btn-primary" do %>
    <i class="fa fa-plus"></i>
    Ajouter une classe pour cet utilisateur
  <% end %>
</div>

<table id="table"
     data-classes="table table-hover table-condensed"
     data-striped="true"
     data-toolbar="#toolbar"
     data-pagination="true"
     data-click-to-select="false"
     data-search="true"
     data-show-export="true"
     data-reorderable-columns="true"
     data-show-refresh="true"
     data-show-pagination-switch="true">
  <thead>
    <tr>
      <th>Classe</th>
      <th>Cycle</th>
      <th>Niveaux</th>
      <th>Etablissement</th>
      <th>Circonscription</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.classrooms.each do |classroom| %>
    <tr>
      <td><%= classroom.name %></td>
      <td><ul>
        <% classroom.cycles.each do |cycle| %>
          <li><%= cycle.name %></li>
        <% end %>
      </ul></td>
      <td><ul>
        <% classroom.levels.each do |level| %>
          <li><%= level.name %></li>
        <% end %>
      </ul></td>
      <td><%= classroom.ecole %></td>
      <td><%= classroom.circonscription && classroom.circonscription.name %></td>
      <td>
        <%= link_to edit_classroom_path(classroom) do %>
          <i class="fa fa-pencil fa-fw"></i>
        <% end %>
      <td>
        <%= link_to classroom, method: :delete, data: { confirm: 'Etes-vous sûr de vouloir supprimer cette classe ?' } do %>
          <i class="fa fa-trash fa-fw"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/account.erb
<div class="form-box">

  <%= form_for @user do |f| %>
    <%= render 'shared/errors', object: @user %>

    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-user"></i></span>
      <%= f.text_field :last_name, class: "form-control", placeholder: "Nom" %>
    </div>

    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-user"></i></span>
      <%= f.text_field :first_name, class: "form-control", placeholder: "Prénom" %>
    </div>

    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-key"></i></span>
      <%= f.password_field :password, class: "form-control", placeholder: "Mot de passe" %>
    </div>

    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-key"></i></span>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmation du mot de passe" %>
    </div>

    <%= f.submit "Modifier", class: 'btn btn-primary login' %>
    <br/><br/>
    <%= link_to "Se désinscrire de Défiweb", @user, method: :delete, data: { confirm: 'Etes-vous sûr de vouloir vous désinscrire de Défiweb ?' }, class:"btn btn-warning login" %>

    <br/><br/>
    <%= link_to 'Retour', root_path %>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="form-box">

  <%= form_for @user do |f| %>
    <%= render 'shared/errors', object: @user %>

    <div class="col-md-6">
      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <%= f.text_field :last_name, class: "form-control", placeholder: "Nom" %>
      </div>

      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <%= f.text_field :first_name, class: "form-control", placeholder: "Prénom" %>
      </div>

      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
        <%= f.text_field :email, class: "form-control", placeholder: "Courriel académique", value: @user.email.to_s, readonly: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <p>Dernière connexion le : <%= @user.current_login_at && @user.current_login_at.strftime("%d/%m/%Y à %Hh%M") %></p>
        <p>Dernière adresse ip : <%= @user.current_login_ip %></p>
        <p>Nombre de connexions réussies : <%= @user.login_count %></p>
        <p>Nombre d'échecs de connexion : <%= @user.failed_login_count %></p>
      </div>
    </div>

    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-key"></i></span>
      <%= f.password_field :password, class: "form-control", placeholder: "Mot de passe" %>
    </div>

    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-key"></i></span>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmation du mot de passe" %>
    </div>

    <div class="col-md-3">
      <div class="well">
        <p>actif ? <%= f.check_box :active, value: @user.active ? 1 : 0, class: "my-checkbox" %></p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well">
        <p>admin ? <%= f.check_box :admin, value: @user.admin ? 1 : 0, class: "my-checkbox" %></p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well">
        <p>pilote ? <%= f.check_box :pilote, value: @user.pilote ? 1 : 0, class: "my-checkbox" %></p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well">
        <p>bloqué ? <%= f.check_box :bloque, value: @user.bloque ? 1 : 0, class: "my-checkbox" %></p>
      </div>
    </div>

    <div class="col-md-12">
      <div class="well">
        <%= render 'classrooms' %>
      </div>
    </div>

    <%= f.submit "Modifier", class: 'btn btn-primary login' %>
    <br/><br/>
    <%= link_to 'Retour', users_path %><br/>
  <% end %>

</div>

app/views/users/emails.html.erb
<% @cycles.each do |key, value| %>
  <div class="col-md-6">
    <h1><%= key %></h1>
    <%= text_area_tag key, value, class: "form-control", rows: 10  %>
  </div>
<% end %>

<div class="end_page"></div>

app/views/users/index.html.erb
<div id="toolbar">
  <%= link_to new_user_path, class: "btn btn-primary" do %>
    <i class="fa fa-plus"></i>
    Ajouter un utilisateur
  <% end %>
  <%= link_to '/users/emails', class: "btn btn-info" do %>
    <i class="fa fa-message-o"></i>
    Exporter courriels
  <% end %>
</div>

<table id="table"
     data-classes="table table-hover table-condensed"
     data-striped="true"
     data-toolbar="#toolbar"
     data-pagination="true"
     data-click-to-select="false"
     data-search="true"
     data-show-export="true"
     data-reorderable-columns="true"
     data-show-refresh="true"
     data-show-pagination-switch="true">
  <thead>
    <tr>
      <th data-sortable="true">Nom</th>
      <th data-sortable="true">Email</th>
      <th data-sortable="true">Classes</th>
      <th data-sortable="true">Actif</th>
      <th data-sortable="true">Dernier login le</th>
      <th data-sortable="true">Login count</th>
      <th data-sortable="true">Création</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.name %>
          <% if user.admin %>
            <i class="fa fa-star-o" title="admin"></i>
          <% end %>
        </td>
        <td><%= user.email %></td>
        <td><ul>
          <% user.classrooms.each do |classroom| %>
            <li><%= "#{classroom.name}, #{classroom.ecole}, circonscription de #{classroom.circonscription && classroom.circonscription.name}" %></li>
          <% end %>
        </ul></td>
        <td>
          <% if user.active %>
            <i class="fa fa-check" title="true"></i>
          <% else %>
            <a onclick="sendActivation(<%= user.id %>)" title="Renvoyer le courriel d'activation"><i class="fa fa-envelope" title="false"></i></a>
          <% end %>
        </td>
        <td><%= user.current_login_at && user.current_login_at.strftime("%Y/%m/%d %Hh%M") %></td>
        <td><%= user.login_count %></td>
        <td><%= user.created_at.strftime("%Y/%m/%d %H:%M") %></td>
        <td>
          <%= link_to edit_user_path(user) do %>
            <i class="fa fa-pencil fa-fw"></i>
          <% end %>
        </td>
        <td>
          <%= link_to user, method: :delete, data: { confirm: 'Etes-vous sûr de vouloir supprimer cet utilisateur ?' } do %>
            <i class="fa fa-trash fa-fw"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="form-box">

  <%= form_for @user do |f| %>
    <%= render 'shared/errors', object: @user %>

    <div class="col-md-6">
      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
        <%= f.text_field :last_name, class: "form-control", placeholder: "Nom", required: true %>
      </div>

      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
        <%= f.text_field :first_name, class: "form-control", placeholder: "Prénom", required: true %>
      </div>

  	  <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-envelope fa-fw"></i></span>
        <%= f.text_field :email, class: "form-control", placeholder: "Courriel académique", value: @user.email.to_s, required: true %>
      </div>

      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
        <%= f.password_field :password, class: "form-control", placeholder: "Mot de passe", required: true %>
      </div>

      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmation du mot de passe", required: true %>
      </div>

      <div class="control-group">
    	  <div class="field input-group">
    			<span class="input-group-addon"><i class="fa fa-map-marker fa-fw"></i></span>
          <%= select_tag "circonscription_id", options_for_select(Circonscription.order(:name).collect{|mt| [mt.name, mt.id]}.insert(0, "Choisir une circonscription")), class: "form-control" %>
        </div>
      </div>

      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-building fa-fw"></i></span>
        <%= text_field_tag "etablissement", nil, class: "form-control", placeholder: "Nom de l'établissement", required: true %>
      </div>

      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-envelope fa-fw"></i></span>
        <%= text_field_tag "email_etablissement", nil, class: "form-control", placeholder: "Courriel académique de l'établissement", required: true %>
      </div>

      <div class="control-group">
    	  <div class="field input-group">
    			<span class="input-group-addon"><i class="fa fa-graduation-cap fa-fw"></i></span>
          <%= select_tag "school_type_id", options_for_select(SchoolType.all.collect{|mt| [mt.name, mt.id]}.insert(0, "Choisir un type d'établissement")), class: "form-control" %>
        </div>
      </div>

      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-building fa-fw"></i></span>
        <%= text_field_tag "class_name", nil, class: "form-control", placeholder: "Nom de la classe", required: true %>
      </div>

      <div class="well">
        <p>Choix du Défiweb</p>
        <% @cycles.each do |cycle| %>
          <div class="col-lg-6">
            <div class="field input-group">
              <span class="input-group-addon">
                <%= check_box_tag cycle.name, cycle.id, false, class:"check checkbox_cycle", type:"checkbox", onclick:"validateInscription();"  %>
              </span>
              <div class="form-control"><%= cycle.name %></div>
            </div>
          </div>
        <% end %>
        <br/><br/>
      </div>

      <div class="well">
        <p>Niveaux de classe</p>
        <% @levels.each do |level| %>
          <% if level.name=="autre" %>
            <div class="col-lg-12">
              <div class="field input-group">
                <span class="input-group-addon">
                  <%= check_box_tag level.name, level.id, false, class:"check checkbox_niveau", id:"otherCheck", onclick:"validateInscription();" %>
                </span>
                <%= text_field_tag "other_classroom", nil, class: "form-control", placeholder: "si autre, précisez", id:"otherClassroom" %>
              </div>
            </div>
          <% else %>
            <div class="col-lg-4">
              <div class="field input-group">
                <span class="input-group-addon">
                  <%= check_box_tag level.name, level.id, false, class:"check checkbox_niveau", onclick:"validateInscription();" %>
                </span>
                <div class="form-control"><%= level.name %></div>
              </div>
            </div>
          <% end %>
        <% end %>
        <br/><br/><br/><br/><br/><br/><br/>
      </div>

    </div>

    <div class="col-md-6">
      <div class="well consignes faq">
        <%= markdown(@consigne.description.to_s) if @consigne %>
      </div>
    </div>

    <button id='buttonValidateInscription' class='btn btn-primary login' title="Vous devez compléter tout le formulaire" disabled>S'inscrire</button>
    <br/><br/>
    <%= link_to 'Annuler', :back %><br/>

  <% end %>


</div>

app/views/users/show.html.erb
<p>
  <strong>Nom:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Circonscription:</strong>
  <%= @user.circonscription.name %>
</p>

<p>
  <strong>Etablissement:</strong>
  <%= @user.school %>
</p>

<p>
  <strong>Cycle:</strong>
  <%= @user.cycle.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<p>
  <strong>Last login at:</strong>
  <%= @user.last_login_at %>
</p>

<p>
  <strong>Current login at:</strong>
  <%= @user.current_login_at %>
</p>

<p>
  <strong>Current login ip:</strong>
  <%= @user.current_login_ip %>
</p>

<p>
  <strong>Last login ip:</strong>
  <%= @user.last_login_ip %>
</p>

<p>
  <strong>Login count:</strong>
  <%= @user.login_count %>
</p>

<p>
  <strong>Failed login count:</strong>
  <%= @user.failed_login_count %>
</p>

<p>
  <strong>Last request at:</strong>
  <%= @user.last_request_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>