config/routes.rb
Rails.application.routes.draw do

  resources :academies
  resources :instructions, only: [:index, :edit, :update]
  resources :configs, only: [:show, :edit, :update]
  get '/results/saisie', to: 'results#saisie'

  resources :results
  resources :notes
  resources :tests
  resources :levels
  resources :classrooms
  resources :school_types
  resources :cycles
  resources :circonscriptions
  resources :documents
  root 'welcome#index'
  get '/global/:id', to: 'welcome#global'
  get '/global', to: redirect('/global/0'), as: :global
  get '/users/:id/active', to: 'users#active', as: :active
  post '/users/:id/send_activation', to: 'users#send_activation', as: :send_activation

  get '/users/emails', to: 'users#emails', as: :emails_path

  get '/faq', to: 'welcome#faq', as: :faq

  get '/account', to: 'users#account', as: :account

  resources :users

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :password_resets, only: [:new, :create, :edit, :update]

  post '/users/new_teacher', to: 'users#create_with_existing_classroom'

  get '/classroom/complet', to: 'classrooms#complet', as: :classroom_complet

  delete '/classrooms/:id/users/:user_id', to: 'classrooms#del_user', as: :classroom_del_user

  get '/tests/:id/documents', to: 'tests#documents'

end

app/models/academie.rb
class Academie < ActiveRecord::Base
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :circonscription
  belongs_to :school_type
  has_and_belongs_to_many :users
  has_and_belongs_to_many :levels
  has_and_belongs_to_many :cycles
  has_many :results

  def cycle?(cycle_id)
    return self.cycle_ids.include?(cycle_id)
  end

  def level?(level_id)
    return self.level_ids.include?(level_id)
  end

end

app/models/config.rb
class Config < ActiveRecord::Base
  has_attached_file :image_fond, styles: { medium: "1200x1200", thumb: "100x100" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image_fond, content_type: /\Aimage\/.*\z/
  has_attached_file :bandeau, styles: { medium: "480x150", thumb: "100x100" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :bandeau, content_type: /\Aimage\/.*\z/
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  has_and_belongs_to_many :classrooms
  has_many :results
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :cycle
  belongs_to :test
  validates :cycle, :test, :presence => true
  has_attached_file :file
  validates_attachment_presence :file
  validates_attachment_file_name :file, matches: [/pdf\z/, /zip\z/]
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_and_belongs_to_many :classrooms
end

app/models/note.rb
class Note < ActiveRecord::Base
  has_attached_file :picto, styles: { medium: "300x300>", thumb: "100x100>", xs: "50x50" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picto, content_type: /\Aimage\/.*\z/
  has_many :results
end

app/models/result.rb
class Result < ActiveRecord::Base
  validates :classroom_id, :test_id, :cycle_id, :note_id, :user_id, :presence => true
  belongs_to :classroom
  belongs_to :test
  belongs_to :cycle
  belongs_to :note
  belongs_to :user
end

app/models/school_type.rb
class SchoolType < ActiveRecord::Base
  has_many :classrooms
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :results
  has_attached_file :picto, styles: { medium: "300x300>", thumb: "100x100>", xs: "50x50" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picto, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :first_name, :last_name, :presence => true

  validate :verify_email

  has_and_belongs_to_many :classrooms
  has_many :results

  acts_as_authentic do |c|
    c.log_in_after_create = false
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end

  def name
    return "#{self.first_name} #{self.last_name.upcase}"
  end

  private
    def verify_email
      address = self.email.downcase
      match = Academie.pluck(:name).detect { |name| address.end_with?(name) }
      errors.add(:email, "Votre courriel ne correspond pas à une adresse académique") unless match
    end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = current_user
    if !@user
      redirect_to sign_in_path
    elsif @user.bloque
      message = "Votre compte utilisateur est bloqué. Veuillez contacter un administrateur"
      current_user_session.destroy
      redirect_to root_path, notice: message
    end
  @tests = Test.all
  end

  def global
    @cycle = params[:id].to_i>0 ? Cycle.find(params[:id]) : nil
    @titre = "Tous les résultats"
    @titre += " du #{@cycle.name}" if @cycle
    @vide = params["vide"]=="1"
    classrooms = Classroom.joins(:circonscription).order("circonscriptions.name", "name")
    @classrooms = []
    if @cycle
      classrooms.each do |classroom|
        @classrooms << classroom
      end
    else
      @classrooms = classrooms.joins(:circonscription).order("circonscriptions.name", "name")
    end
    @cycles = Cycle.order(:name)
    @tests = Test.order(:order)
    @test = params["test_id"].to_i>0 ? Test.find(params["test_id"].to_i) : nil
  end

end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def delete user
    if user.results.count>0
      user.active = false
      user.save
      return false
    else
      user.classrooms.each do |classroom|
        unless classroom.users.count>1
          classroom.destroy
        end
      end
      user.destroy
      return true
    end
  end

end

app/views/welcome/faq.erb
<% faq = Instruction.where(name: "faq").first %>
<% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML) %>
<div class="well faq">
  <%= markdown(faq.description) %>
</div>
<%= link_to 'Retour', "/" %><br/>

app/views/welcome/global.html.erb
<% unless current_user %>
  <nav class="navbar navbar-inverse">
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a aria-expanded="false" href="#" class="dropdown-toggle" data-toggle="dropdown" title="Voir tous les résultats">Voir tous les résultats <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Tous les cyles", "/global/0" %></li>
            <% Cycle.order(:name).each do |cycle| %>
              <li><%= link_to cycle.name, "/global/#{cycle.id}" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Se connecter', sign_in_path %></li>
      </ul>
    </div>
  </nav>
<% end %>

<h2><%= @titre %></h2>

<div class="col-md-12">
  <div id="toolbar">
    <div class="control-group">
      <div class="field input-group">
        <span class="input-group-addon"><i class="fa fa-pencil fa-fw"></i></span>
        <%= select_tag "test_id", options_for_select(@tests.collect{|mt| [mt.name, mt.id]}.insert(0, "Toutes les épreuves"), @test && @test.id), class: "form-control", id: "test_id", onchange: "selectTest(#{@cycle && @cycle.id})" %>
      </div>
    </div>
  </div>
</div>

<table id="table"
     data-classes="table table-condensed table-xs"
     data-striped="false"
     data-toolbar="#toolbar"
     data-pagination="true"
     data-click-to-select="false"
     data-search="true"
     data-show-export="true"
     data-reorderable-columns="false"
     data-show-refresh="false"
     data-show-pagination-switch="false">
  <thead>
    <tr>
      <th>Circonscription</th>
      <th>Cycles</th>
      <th>Etablissement</th>
      <th>Classes</th>
      <th>Niveaux</th>
      <th>Enseignants</th>
      <% if @test %>
        <th title="<%= @test.name %>" align="center">
          <%= image_tag @test.picto.url(:xs) %>
        </th>
      <% else %>
        <% @tests.each do |test| %>
          <th title="<%= test.name %>">
            <%= image_tag test.picto.url(:xs) %>
          </th>
        <% end %>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <% classroom.cycles.each do |cycle| %>
        <% if (!@cycle or (@cycle && @cycle.id==cycle.id)) %>
          <% count = Result.where(classroom_id: classroom.id, cycle_id: cycle.id).count %>
          <% if (count>0 or @vide) %>
            <tr>
              <td><%= classroom.circonscription && classroom.circonscription.name %></td>
              <td><%= cycle.name %></td>
              <td><%= classroom.ecole %></td>
              <td><%= classroom.name %></td>
              <td><ul>
                <% classroom.levels.each do |level| %>
                  <li><%= (level.name=="autre" ? classroom.other_level : level.name) %></li>
                <% end %>
              </ul></td>
              <td><ul>
                <% nb = classroom.user_ids.count %>
                <% i = 1 %>
                <% classroom.users.each do |user| %>
                  <li><%= "#{user.name}#{i>=nb ? '' : ','}" %></li>
                  <% i += 1 %>
                <% end %>
              </ul></td>
              <% if @test %>
                <td>
                  <% result = Result.where(classroom_id: classroom.id, cycle_id: cycle.id, test_id: @test.id).first %>
                  <% if result %>
                    <%= image_tag result.note.picto.url(:xs), title: "#{@test.name}: #{result.note.name}" %>
                    <br/><p class="white"><%= result.note.value %></p>
                  <% end %>
                </td>
              <% else %>
                <% @tests.each do |test| %>
                  <td>
                    <% result = Result.where(classroom_id: classroom.id, cycle_id: cycle.id, test_id: test.id).first %>
                    <% if result %>
                      <%= image_tag result.note.picto.url(:xs), title: "#{test.name}: #{result.note.name}" %>
                      <br/><p class="white"><%= result.note.value %></p>
                    <% end %>
                  </td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <span class="glyphicon glyphicon-blackboard"></span>
        Mes classes
      </h4>
    </div>
    <div class="panel-collapse collapse">
      <div class="panel-body">
        <div id="toolbar">
          <%= link_to new_classroom_path, class: "btn btn-primary" do %>
            <i class="fa fa-plus"></i>
            Ajouter une nouvelle classe
          <% end %>
        </div>

        <table id="table"
             data-classes="table table-hover table-condensed"
             data-striped="true"
             data-toolbar="#toolbar"
             data-pagination="false"
             data-click-to-select="false"
             data-search="false"
             data-show-export="false"
             data-reorderable-columns="false"
             data-show-refresh="false"
             data-show-pagination-switch="false">
          <thead>
            <tr>
              <th>Classe</th>
              <th>Cycle</th>
              <th>Niveaux</th>
              <th>Etablissement</th>
              <th>Type d'établissement</th>
              <th>Circonscription</th>
              <th>Autres enseignants</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @user.classrooms.each do |classroom| %>
              <tr>
                <td><%= classroom.name %></td>
                <td>
                  <% classroom.cycles.each do |cycle| %>
                    <%= link_to "/results/saisie?classroom_id=#{classroom.id};cycle_id=#{cycle.id}", class: "btn btn-info btn-sm" do %>
                      <i class="fa fa-pencil"></i>
                      <%= cycle.name %> : Saisir les résultats
                    <% end %>
                  <% end %>
                </td>
                <td><ul>
                  <% classroom.levels.each do |level| %>
                    <li><%= (level.name=="autre" ? classroom.other_level : level.name) %></li>
                  <% end %>
                </ul></td>
                <td><%= classroom.ecole %></td>
                <td><%= classroom.school_type && classroom.school_type.name %></td>
                <td><%= classroom.circonscription && classroom.circonscription.name %></td>
                <td>
                  <% if classroom.users.count>1 %>
                    <ul>
                      <% classroom.users.each do |user| %>
                        <% if @user.id!=user.id %>
                          <li>
                            <%= user.name %>
                            <% if current_user.admin %>
                              <%= link_to "-", "/classrooms/#{classroom.id}/users/#{user.id}", method: "delete" %>
                            <% end %>
                          </li>
                        <% end %>
                      <% end %>
                    </ul>
                  <% end %>
                  <button type="button" class="btn btn-info btn-sm boutonAfficheModaleAjoutEnseignant" value="<%= classroom.id %>">
                    <i class="fa fa-plus"></i> Ajouter un enseignant
                  </button>
                </td>
                <td>
                  <%= link_to edit_classroom_path(classroom) do %>
                    <i class="fa fa-pencil fa-fw"></i>
                  <% end %>
                </td>
                <td>
                  <%= link_to "/classrooms/#{classroom.id}/users/#{current_user.id}", method: :delete, data: { confirm: "Etes-vous sûr de vouloir retirer cette classe de votre liste ?" } do %>
                    <i class="fa fa-trash fa-fw"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <span class="glyphicon glyphicon-book"></span>
        Mes documents
      </h4>
    </div>
    <div class="panel-collapse collapse">
      <div class="panel-body">
        <table id="table_docs"
             data-classes="table table-hover table-condensed"
             data-striped="true"
             data-pagination="false"
             data-click-to-select="false"
             data-search="false"
             data-show-export="false"
             data-reorderable-columns="false"
             data-show-refresh="false"
             data-show-pagination-switch="false">
          <thead>
            <tr>
              <th>Epreuves</th>
              <th>Cycles</th>
              <th>
                Documents
                <% if @user.admin %>
                  <%= link_to new_document_path do %>
                    <span class="glyphicon glyphicon-plus"></span>
                  <% end %>
                <% end %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% rows = Cycle.all.count %>
            <% @tests.each do |test| %>
              <% i = 0 %>
              <% Cycle.all.each do |cycle| %>
                <% i += 1 %>
                <tr>
                  <% if i==1 %>
                    <td rowspan="<%= rows %>"><%= image_tag test.picto.url(:thumb) %><%= test.name %></td>
                  <% end %>
                  <td valign="middle"><%= cycle.name %></td>
                  <td>
                    <% Document.where(cycle_id: cycle.id, test_id: test.id).each do |document| %>
                      <%= link_to document.file.url, target: "_blank", title: "#{document.description}" do %>
                        <span class="glyphicon glyphicon-book"></span>
                        <%= document.name %>
                      <% end %>
                      <br/>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- Modale d'ajout d'un enseignant à la classe -->
<div id="modaleAjoutEnseignant" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-m">
    <div class="modal-content">
      <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button> <h4 class="modal-title" id="mySmallModalLabel">Ajout d'un nouvel enseignant pour cette classe</h4> </div>
      <div class="modal-body">

        <%= form_tag('/users/new_teacher') do %>
          <%= number_field_tag "classroom_id", nil, id: "fieldClassroomId", hidden: true %>

          <div class="field input-group">
            <span class="input-group-addon"><i class="fa fa-user"></i></span>
            <%= text_field_tag "last_name", nil, class: "form-control", placeholder: "Nom" %>
          </div>

          <div class="field input-group">
            <span class="input-group-addon"><i class="fa fa-user"></i></span>
            <%= text_field_tag "first_name", nil, class: "form-control", placeholder: "Prénom" %>
          </div>

      	  <div class="field input-group">
            <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
            <%= text_field_tag "email", nil, class: "form-control", placeholder: "Courriel académique" %>
          </div>

          <%= button_tag "Ajouter", id: "boutonAjoutEnseignant", class: "btn btn-primary" %>
        <% end %>

      </div>
    </div>
  </div>
</div>