config/routes.rb
Rails.application.routes.draw do

  resources :academies
  resources :instructions, only: [:index, :edit, :update]
  resources :configs, only: [:show, :edit, :update]
  get '/results/saisie', to: 'results#saisie'

  resources :results
  resources :notes
  resources :tests
  resources :levels
  resources :classrooms
  resources :school_types
  resources :cycles
  resources :circonscriptions
  resources :documents
  root 'welcome#index'
  get '/global/:id', to: 'welcome#global'
  get '/global', to: redirect('/global/0'), as: :global
  get '/users/:id/active', to: 'users#active', as: :active
  post '/users/:id/send_activation', to: 'users#send_activation', as: :send_activation

  get '/users/emails', to: 'users#emails', as: :emails_path

  get '/faq', to: 'welcome#faq', as: :faq

  get '/account', to: 'users#account', as: :account

  resources :users

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :password_resets, only: [:new, :create, :edit, :update]

  post '/users/new_teacher', to: 'users#create_with_existing_classroom'

  get '/classroom/complet', to: 'classrooms#complet', as: :classroom_complet

  delete '/classrooms/:id/users/:user_id', to: 'classrooms#del_user', as: :classroom_del_user

  get '/tests/:id/documents', to: 'tests#documents'

end

app/models/academie.rb
class Academie < ActiveRecord::Base
end

app/models/circonscription.rb
class Circonscription < ActiveRecord::Base
  has_many :users
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :circonscription
  belongs_to :school_type
  has_and_belongs_to_many :users
  has_and_belongs_to_many :levels
  has_and_belongs_to_many :cycles
  has_many :results

  def cycle?(cycle_id)
    return self.cycle_ids.include?(cycle_id)
  end

  def level?(level_id)
    return self.level_ids.include?(level_id)
  end

end

app/models/config.rb
class Config < ActiveRecord::Base
  has_attached_file :image_fond, styles: { medium: "1200x1200", thumb: "100x100" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image_fond, content_type: /\Aimage\/.*\z/
  has_attached_file :bandeau, styles: { medium: "480x150", thumb: "100x100" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :bandeau, content_type: /\Aimage\/.*\z/
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  has_and_belongs_to_many :classrooms
  has_many :results
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :cycle
  belongs_to :test
  validates :cycle, :test, :presence => true
  has_attached_file :file
  validates_attachment_presence :file
  validates_attachment_file_name :file, matches: [/pdf\z/, /zip\z/]
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
end

app/models/level.rb
class Level < ActiveRecord::Base
  has_and_belongs_to_many :classrooms
end

app/models/note.rb
class Note < ActiveRecord::Base
  has_attached_file :picto, styles: { medium: "300x300>", thumb: "100x100>", xs: "50x50" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picto, content_type: /\Aimage\/.*\z/
  has_many :results
end

app/models/result.rb
class Result < ActiveRecord::Base
  validates :classroom_id, :test_id, :cycle_id, :note_id, :user_id, :presence => true
  belongs_to :classroom
  belongs_to :test
  belongs_to :cycle
  belongs_to :note
  belongs_to :user
end

app/models/school_type.rb
class SchoolType < ActiveRecord::Base
  has_many :classrooms
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :results
  has_attached_file :picto, styles: { medium: "300x300>", thumb: "100x100>", xs: "50x50" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picto, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :first_name, :last_name, :presence => true

  validate :verify_email

  has_and_belongs_to_many :classrooms
  has_many :results

  acts_as_authentic do |c|
    c.log_in_after_create = false
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end

  def name
    return "#{self.first_name} #{self.last_name.upcase}"
  end

  private
    def verify_email
      address = self.email.downcase
      match = Academie.pluck(:name).detect { |name| address.end_with?(name) }
      errors.add(:email, "Votre courriel ne correspond pas à une adresse académique") unless match
    end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :only_admins, except: [:index]
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /tests/:id/documents
  # GET /tests/:id/documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to "/", notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to "/", notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :description, :file, :cycle_id, :test_id)
    end
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def delete user
    if user.results.count>0
      user.active = false
      user.save
      return false
    else
      user.classrooms.each do |classroom|
        unless classroom.users.count>1
          classroom.destroy
        end
      end
      user.destroy
      return true
    end
  end

end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-pencil fa-fw"></i></span>
      <%= f.select :test_id, options_for_select(Test.order(:name).collect{|mt| [mt.name, mt.id]}.insert(0, "Choisir une épreuve"), @document.test_id), {}, class: "form-control" %>
    </div>
  </div>

  <div class="control-group">
    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-graduation-cap fa-fw"></i></span>
      <%= f.select :cycle_id, options_for_select(Cycle.order(:name).collect{|mt| [mt.name, mt.id]}.insert(0, "Choisir un cycle"), @document.cycle_id), {}, class: "form-control" %>
    </div>
  </div>

  <div class="field input-group">
    <span class="input-group-addon"><i class="fa fa-pencil fa-fw"></i></span>
    <%= f.text_field :name, class: "form-control", placeholder: "Nom du document" %>
  </div>

  <div class="field input-group">
    <span class="input-group-addon"><i class="fa fa-pencil fa-fw"></i></span>
    <%= f.text_area :description, class: "form-control", placeholder: "Description du document" %>
  </div>

  <div class="field">
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit "Valider", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>File</th>
      <th>Cycle</th>
      <th>Test</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.description %></td>
        <td><%= document.file %></td>
        <td><%= document.cycle %></td>
        <td><%= document.test %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>Nouveau document</h1>

<%= render 'form' %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @document.description %>
</p>

<p>
  <strong>File:</strong>
  <%= @document.file %>
</p>

<p>
  <strong>Cycle:</strong>
  <%= @document.cycle %>
</p>

<p>
  <strong>Test:</strong>
  <%= @document.test %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>